import React, { useState, useMemo } from 'react';
import { generatePattern } from '../services/geminiService';
import { GeneratedPattern } from '../types';
import { IconDownload, IconLoader, IconZap, IconCode, IconX } from './Icons';

const Tooltip = ({ children, text, className = "" }: { children: React.ReactNode; text: string; className?: string }) => (
  <div className={`group relative ${className}`}>
    {children}
    <div className="absolute bottom-full left-1/2 transform -translate-x-1/2 mb-2 w-auto max-w-[200px] whitespace-normal px-3 py-2 bg-slate-900 text-slate-200 text-xs rounded-lg opacity-0 group-hover:opacity-100 transition-all duration-200 pointer-events-none z-50 border border-slate-700 shadow-xl text-center backdrop-blur-sm">
      {text}
      <div className="absolute top-full left-1/2 transform -translate-x-1/2 border-4 border-transparent border-t-slate-700"></div>
    </div>
  </div>
);

const PatternGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [pattern, setPattern] = useState<GeneratedPattern | null>(null);
  const [showGCode, setShowGCode] = useState(false);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setLoading(true);
    setPattern(null);
    try {
      const result = await generatePattern(prompt);
      setPattern(result);
    } catch (e) {
      const msg = (e as any)?.message || "Failed to generate pattern. Please try again.";
      alert(msg);
    } finally {
      setLoading(false);
    }
  };

  // Construct SVG Path string from points
  // NOTE: SVG Coordinate system has (0,0) at top-left.
  // We requested Cartesian coordinates from AI where (0,0) is bottom-left.
  // Therefore, we must invert the Y axis for visualization: svgY = 100 - p.y
  const svgPathData = useMemo(() => {
    if (!pattern || !pattern.points || pattern.points.length === 0) return '';
    const pts = pattern.points;
    const isClosed =
      pts.length > 2 &&
      Math.abs(pts[0].x - pts[pts.length - 1].x) < 1e-6 &&
      Math.abs(pts[0].y - pts[pts.length - 1].y) < 1e-6;

    const body = `M ${pts[0].x} ${100 - pts[0].y} ` +
      pts.slice(1).map(p => `L ${p.x} ${100 - p.y}`).join(' ');

    return isClosed ? `${body} Z` : body;
  }, [pattern]);

  // Generators
  const generateGCode = () => {
    if (!pattern) return '';
    const points = pattern.points;
    const date = new Date().toLocaleDateString();
    let gcode = `%; Filename: ${pattern.name.replace(/\s+/g, '_')}.nc
; Generated by FoamForge on ${date}
; Material: Generic Foam
G21 ; Units in mm
G90 ; Absolute positioning
G17 ; XY Plane selection
; Start Sequence
G0 X${points[0].x.toFixed(3)} Y${points[0].y.toFixed(3)} ; Rapid to start
M3 ; Turn on spindle/wire
G4 P1 ; Dwell 1s for wire heat
F300 ; Set Feed rate 300 mm/min
`;

    points.forEach((p, i) => {
        if (i > 0) {
            gcode += `G1 X${p.x.toFixed(3)} Y${p.y.toFixed(3)}\n`;
        }
    });

    gcode += `; End Sequence
M5 ; Turn off wire
G0 X0 Y0 ; Return to home
M2 ; End of program
%`;
    return gcode;
  };

  const generateDXF = () => {
    if (!pattern) return '';
    const points = pattern.points;
    const isClosed =
      points.length > 2 &&
      Math.abs(points[0].x - points[points.length - 1].x) < 1e-6 &&
      Math.abs(points[0].y - points[points.length - 1].y) < 1e-6;
    let dxf = `0
SECTION
2
HEADER
9
$ACADVER
1
AC1009
0
ENDSEC
0
SECTION
2
ENTITIES
0
LWPOLYLINE
8
0
100
AcDbEntity
100
AcDbPolyline
90
${points.length}
70
${isClosed ? 1 : 0}
`; // 70 1 = Closed polyline, 70 0 = Open polyline

    points.forEach(p => {
        dxf += `10\n${p.x.toFixed(4)}\n20\n${p.y.toFixed(4)}\n`;
    });

    dxf += `0
ENDSEC
0
EOF
`;
    return dxf;
  };

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  const handleDownloadSVG = () => {
    if (!pattern) return;
    const svgContent = `
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
        <!-- SVG normally has 0,0 at top left. To match our preview, we can transform it or map points. -->
        <!-- Mapping points to keep it simple for generic SVG viewers -->
        <path d="${svgPathData}" fill="none" stroke="black" stroke-width="0.5" />
      </svg>
    `;
    downloadFile(svgContent, `${pattern.name.replace(/\s+/g, '_').toLowerCase()}.svg`, 'image/svg+xml');
  };

  const handleDownloadGCode = () => {
      if (!pattern) return;
      const content = generateGCode();
      downloadFile(content, `${pattern.name.replace(/\s+/g, '_').toLowerCase()}.nc`, 'text/plain');
  };

  const handleDownloadDXF = () => {
      if (!pattern) return;
      const content = generateDXF();
      downloadFile(content, `${pattern.name.replace(/\s+/g, '_').toLowerCase()}.dxf`, 'application/dxf');
  };

  return (
    <div className="max-w-4xl mx-auto w-full p-4 space-y-8 animate-fade-in relative">
      <div className="text-center space-y-2">
        <h2 className="text-3xl font-bold text-white">AI Pattern Generator</h2>
        <p className="text-slate-400">Describe a shape, wing profile, or letter, and we'll generate a continuous cut path.</p>
      </div>

      <div className="grid md:grid-cols-2 gap-8 items-start">
        
        {/* Input Section */}
        <div className="space-y-6 bg-slate-800 p-6 rounded-2xl border border-slate-700 shadow-xl">
          <div className="space-y-2">
            <label className="block text-sm font-medium text-slate-300">Description</label>
            <Tooltip text="Describe the shape you want to cut. Be specific about continuous lines for hot wire cutting." className="block w-full">
              <textarea
                className="w-full bg-slate-900 border border-slate-600 rounded-lg p-3 text-white placeholder-slate-500 focus:ring-2 focus:ring-hot-wire-500 focus:border-transparent outline-none transition-all resize-none h-32"
                placeholder="e.g. A futuristic sword handle with finger grooves..."
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
              />
            </Tooltip>
          </div>

          <Tooltip text="Uses AI to generate a continuous vector path based on your description." className="block w-full">
            <button
              onClick={handleGenerate}
              disabled={loading || !prompt}
              className={`w-full py-3 px-6 rounded-lg font-bold flex items-center justify-center gap-2 transition-all
                ${loading || !prompt 
                  ? 'bg-slate-700 text-slate-500 cursor-not-allowed' 
                  : 'bg-gradient-to-r from-hot-wire-600 to-hot-wire-500 hover:from-hot-wire-500 hover:to-hot-wire-400 text-white shadow-[0_0_20px_rgba(249,115,22,0.3)] hover:shadow-[0_0_30px_rgba(249,115,22,0.5)] transform hover:-translate-y-0.5'
                }`}
            >
              {loading ? <IconLoader className="animate-spin" /> : <IconZap />}
              {loading ? 'Generating Path...' : 'Ignite Generator'}
            </button>
          </Tooltip>
        </div>

        {/* Preview Section */}
        <div className="space-y-4">
          <div className="aspect-square w-full bg-slate-900 rounded-2xl border-2 border-slate-700 border-dashed flex items-center justify-center relative overflow-hidden group">
            {pattern ? (
              <div className="relative w-full h-full p-8 transition-all duration-500 ease-out transform">
                 {/* Grid Background */}
                 <div className="absolute inset-0 opacity-10 pointer-events-none" 
                      style={{backgroundImage: 'radial-gradient(circle, #fff 1px, transparent 1px)', backgroundSize: '20px 20px'}}>
                 </div>
                 
                 {/* The Generated SVG */}
                 <svg viewBox="0 0 100 100" className="w-full h-full drop-shadow-[0_0_8px_rgba(249,115,22,0.8)] overflow-visible">
                    {/* Origin Marker */}
                    <circle cx="0" cy="100" r="1.5" fill="#f97316" className="animate-pulse" />
                    <text x="2" y="98" fontSize="3" fill="#64748b">0,0</text>

                    <path 
                      d={svgPathData} 
                      fill="none" 
                      stroke="#fb923c" 
                      strokeWidth="0.8" 
                      strokeLinecap="round" 
                      strokeLinejoin="round"
                      className="animate-[dash_3s_ease-in-out_forwards]"
                    />
                    {/* Render dots for points to visualize density, limit to avoid clutter if high density */}
                     {pattern.points.length < 150 && pattern.points.map((p, i) => (
                        <circle key={i} cx={p.x} cy={100 - p.y} r="0.5" fill="#fff" opacity="0.3" />
                     ))}
                 </svg>
              </div>
            ) : (
              <div className="text-center text-slate-600">
                <IconZap className="w-12 h-12 mx-auto mb-2 opacity-20" />
                <p>Preview Area</p>
              </div>
            )}
            
            {/* Loading Overlay */}
            {loading && (
              <div className="absolute inset-0 bg-slate-900/80 backdrop-blur-sm flex items-center justify-center z-10">
                <div className="flex flex-col items-center gap-3">
                   <div className="w-12 h-1 bg-slate-700 rounded-full overflow-hidden">
                     <div className="h-full bg-hot-wire-500 animate-progress"></div>
                   </div>
                   <span className="text-xs text-hot-wire-400 font-mono animate-pulse">CALCULATING VECTORS...</span>
                </div>
              </div>
            )}
          </div>

          {pattern && (
             <div className="bg-slate-800 p-4 rounded-xl border border-slate-700 animate-fade-in-up">
                <div className="mb-4">
                    <h3 className="text-lg font-bold text-white">{pattern.name}</h3>
                    <div className="flex gap-2 mt-2">
                        <span className="text-xs px-2 py-0.5 rounded-full bg-slate-700 text-slate-300 border border-slate-600">{pattern.difficulty}</span>
                        <span className="text-xs px-2 py-0.5 rounded-full bg-slate-700 text-slate-300 border border-slate-600">{pattern.estimatedCutTime}</span>
                        <span className="text-xs px-2 py-0.5 rounded-full bg-slate-700 text-slate-300 border border-slate-600">{pattern.points.length} nodes</span>
                    </div>
                </div>
                
                <p className="text-sm text-slate-400 mb-4">{pattern.description}</p>
                
                <div className="grid grid-cols-2 gap-3">
                    <button onClick={handleDownloadSVG} className="py-2.5 px-3 bg-slate-700 hover:bg-slate-600 rounded-lg text-xs text-white font-medium transition-colors flex items-center justify-center gap-2 border border-slate-600">
                        <IconDownload className="w-4 h-4" /> Download SVG
                    </button>
                    <button onClick={handleDownloadDXF} className="py-2.5 px-3 bg-slate-700 hover:bg-slate-600 rounded-lg text-xs text-white font-medium transition-colors flex items-center justify-center gap-2 border border-slate-600">
                         <span className="font-mono font-bold text-sm">D</span> Download DXF
                    </button>
                    <button onClick={() => setShowGCode(true)} className="py-2.5 px-3 bg-slate-700 hover:bg-slate-600 rounded-lg text-xs text-white font-medium transition-colors flex items-center justify-center gap-2 border border-slate-600">
                        <IconCode className="w-4 h-4" /> View G-Code
                    </button>
                     <button onClick={handleDownloadGCode} className="py-2.5 px-3 bg-hot-wire-600 hover:bg-hot-wire-500 rounded-lg text-xs text-white font-medium transition-colors flex items-center justify-center gap-2 border border-hot-wire-500 shadow-lg shadow-hot-wire-600/10">
                        <span className="font-mono font-bold text-sm">G</span> Download .NC
                    </button>
                </div>
             </div>
          )}
        </div>
      </div>

      {/* G-Code Modal */}
      {showGCode && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/80 backdrop-blur-sm animate-fade-in">
            <div className="bg-slate-800 border border-slate-700 rounded-2xl w-full max-w-2xl max-h-[80vh] flex flex-col shadow-2xl overflow-hidden">
                <div className="flex justify-between items-center p-4 border-b border-slate-700 bg-slate-800/50">
                    <h3 className="text-lg font-bold text-white flex items-center gap-2">
                        <IconCode className="w-5 h-5 text-hot-wire-500"/> G-Code Preview
                    </h3>
                    <button onClick={() => setShowGCode(false)} className="text-slate-400 hover:text-white transition-colors">
                        <IconX className="w-6 h-6" />
                    </button>
                </div>
                <div className="flex-1 overflow-auto p-0 bg-slate-950 relative group">
                    <pre className="p-4 font-mono text-xs md:text-sm text-green-400 leading-relaxed whitespace-pre-wrap">
                        {generateGCode()}
                    </pre>
                </div>
                <div className="p-4 border-t border-slate-700 bg-slate-800 flex justify-end gap-3">
                    <button onClick={() => setShowGCode(false)} className="px-4 py-2 text-slate-300 hover:text-white text-sm font-medium">
                        Close
                    </button>
                    <button onClick={handleDownloadGCode} className="px-4 py-2 bg-hot-wire-600 hover:bg-hot-wire-500 text-white rounded-lg text-sm font-bold flex items-center gap-2 shadow-lg shadow-hot-wire-600/20">
                        <IconDownload className="w-4 h-4" /> Download .nc
                    </button>
                </div>
            </div>
        </div>
      )}
    </div>
  );
};

export default PatternGenerator;